CREATE TABLE IF NOT EXISTS Account
(
    ID        BIGINT AUTO_INCREMENT,
    NAME      VARCHAR(30)  NOT NULL,
    PASSWORD  VARCHAR(100) NOT NULL,
    ROLE      VARCHAR(30)  NOT NULL,
    AGE       INTEGER      NOT NULL,
    CREATE_AT DATETIME,
    UPDATE_AT DATETIME,
    CONSTRAINT GUILD_PK PRIMARY KEY (ID)
);